version: "2.32.4"
services:
  mongodb:
    image:  "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./mongo.env

  backend_api:
    image: "pokemon-app-img"
    ports: 
      - "3000:80"
    volumes:
      - logs:/app/logs
      - /app/node_modules



volumes:
  data:


      